[package]
name = "whattime"
version = "1.0.0"
edition = "2021"
description = "See the current time at any time!"
repository = "https://github.com/yesseruser/whattimeisit"
homepage = "https://github.com/yesseruser/whattimeisit"
license = "GPL-3.0"

[dependencies]
chrono = "0.4"