[package]
name = "whattimeisit"
version = "1.0.0"
edition = "2021"
description = "See the current time at any time!"
repository = "https://github.com/yesseruser/whattimeisit"
homepage = "https://github.com/yesseruser/whattimeisit"

[dependencies]
chrono = "0.4"